<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yang Lun">
<meta name="dcterms.date" content="2026-08-14">

<title>TargetC Phenotypes Analysis — Microbial Phenotype Prediction (Traitar / microTrait / dbCAN3)</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="TargetC-phenotypes-analysis-260814_files/libs/clipboard/clipboard.min.js"></script>
<script src="TargetC-phenotypes-analysis-260814_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="TargetC-phenotypes-analysis-260814_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="TargetC-phenotypes-analysis-260814_files/libs/quarto-html/popper.min.js"></script>
<script src="TargetC-phenotypes-analysis-260814_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="TargetC-phenotypes-analysis-260814_files/libs/quarto-html/anchor.min.js"></script>
<link href="TargetC-phenotypes-analysis-260814_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="TargetC-phenotypes-analysis-260814_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="TargetC-phenotypes-analysis-260814_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="TargetC-phenotypes-analysis-260814_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="TargetC-phenotypes-analysis-260814_files/libs/bootstrap/bootstrap-62e2d20df198e8a01bb734742f2e28cf.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#description" id="toc-description" class="nav-link active" data-scroll-target="#description">1. Description</a>
  <ul class="collapse">
  <li><a href="#study-design" id="toc-study-design" class="nav-link" data-scroll-target="#study-design">1.1 Study design</a></li>
  <li><a href="#the-three-phenotype-prediction-tools" id="toc-the-three-phenotype-prediction-tools" class="nav-link" data-scroll-target="#the-three-phenotype-prediction-tools">1.2 The three phenotype-prediction tools</a></li>
  <li><a href="#statistical-methods" id="toc-statistical-methods" class="nav-link" data-scroll-target="#statistical-methods">1.3 Statistical methods</a></li>
  <li><a href="#output-layout" id="toc-output-layout" class="nav-link" data-scroll-target="#output-layout">1.4 Output layout</a></li>
  </ul></li>
  <li><a href="#traitar" id="toc-traitar" class="nav-link" data-scroll-target="#traitar">2. Traitar</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">2.1 Overview</a></li>
  <li><a href="#script" id="toc-script" class="nav-link" data-scroll-target="#script">2.2 Script</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">2.3 Results</a></li>
  <li><a href="#figures" id="toc-figures" class="nav-link" data-scroll-target="#figures">2.4 Figures</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">2.5 Interpretation</a></li>
  </ul></li>
  <li><a href="#microtrait" id="toc-microtrait" class="nav-link" data-scroll-target="#microtrait">3. microTrait</a>
  <ul class="collapse">
  <li><a href="#overview-1" id="toc-overview-1" class="nav-link" data-scroll-target="#overview-1">3.1 Overview</a></li>
  <li><a href="#script-1" id="toc-script-1" class="nav-link" data-scroll-target="#script-1">3.2 Script</a></li>
  <li><a href="#results-1" id="toc-results-1" class="nav-link" data-scroll-target="#results-1">3.3 Results</a></li>
  <li><a href="#figures-1" id="toc-figures-1" class="nav-link" data-scroll-target="#figures-1">3.4 Figures</a></li>
  <li><a href="#interpretation-1" id="toc-interpretation-1" class="nav-link" data-scroll-target="#interpretation-1">3.5 Interpretation</a></li>
  </ul></li>
  <li><a href="#dbcan3" id="toc-dbcan3" class="nav-link" data-scroll-target="#dbcan3">4. dbCAN3</a>
  <ul class="collapse">
  <li><a href="#overview-2" id="toc-overview-2" class="nav-link" data-scroll-target="#overview-2">4.1 Overview</a></li>
  <li><a href="#script-2" id="toc-script-2" class="nav-link" data-scroll-target="#script-2">4.2 Script</a></li>
  <li><a href="#results-2" id="toc-results-2" class="nav-link" data-scroll-target="#results-2">4.3 Results</a></li>
  <li><a href="#figures-2" id="toc-figures-2" class="nav-link" data-scroll-target="#figures-2">4.4 Figures</a></li>
  <li><a href="#interpretation-2" id="toc-interpretation-2" class="nav-link" data-scroll-target="#interpretation-2">4.5 Interpretation</a></li>
  </ul></li>
  <li><a href="#dbcan3-mucin-modules" id="toc-dbcan3-mucin-modules" class="nav-link" data-scroll-target="#dbcan3-mucin-modules">5. dbCAN3 mucin modules</a>
  <ul class="collapse">
  <li><a href="#overview-3" id="toc-overview-3" class="nav-link" data-scroll-target="#overview-3">5.1 Overview</a></li>
  <li><a href="#script-3" id="toc-script-3" class="nav-link" data-scroll-target="#script-3">5.2 Script</a></li>
  <li><a href="#results-3" id="toc-results-3" class="nav-link" data-scroll-target="#results-3">5.3 Results</a></li>
  <li><a href="#figures-3" id="toc-figures-3" class="nav-link" data-scroll-target="#figures-3">5.4 Figures</a></li>
  <li><a href="#interpretation-3" id="toc-interpretation-3" class="nav-link" data-scroll-target="#interpretation-3">5.5 Interpretation</a></li>
  </ul></li>
  <li><a href="#overall-interpretation" id="toc-overall-interpretation" class="nav-link" data-scroll-target="#overall-interpretation">6. Overall interpretation</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">TargetC Phenotypes Analysis — Microbial Phenotype Prediction (Traitar / microTrait / dbCAN3)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yang Lun </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 14, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<style>
  div.sourceCode {
    max-height: 500px;
    overflow-y: auto;
  }
</style>
<section id="description" class="level1">
<h1>1. Description</h1>
<section id="study-design" class="level2">
<h2 class="anchored" data-anchor-id="study-design">1.1 Study design</h2>
<p>The TargetC cohort is an adenoma follow-up study. MAG-level genomes were recovered from 393 metagenomic samples and their <strong>microbial phenotypes were predicted</strong> with three complementary tools. Six clinical groups are compared:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>N</td>
<td>Normal (endoscopy-normal control)</td>
</tr>
<tr class="even">
<td>Re1</td>
<td>Recurrence_1 (adenoma recurrence, 1st sampling)</td>
</tr>
<tr class="odd">
<td>Re2</td>
<td>Recurrence_2 (adenoma recurrence, 2nd sampling)</td>
</tr>
<tr class="even">
<td>Non1</td>
<td>Non_recurrence_1 (adenoma non-recurrence, 1st sampling)</td>
</tr>
<tr class="odd">
<td>Non2</td>
<td>Non_recurrence_2 (adenoma non-recurrence, 2nd sampling)</td>
</tr>
<tr class="even">
<td>CRC</td>
<td>CRC</td>
</tr>
</tbody>
</table>
<p>The main biological question is the <strong>adenoma follow-up subset</strong> (4 groups: Re1 / Re2 / Non1 / Non2, n = 236 samples, 59 per group): do the predicted phenotypes of the gut microbiome differ between subjects whose adenoma recurred and those who did not, and do they change between the two samplings?</p>
</section>
<section id="the-three-phenotype-prediction-tools" class="level2">
<h2 class="anchored" data-anchor-id="the-three-phenotype-prediction-tools">1.2 The three phenotype-prediction tools</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 46%">
<col style="width: 17%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Tool</th>
<th>What it predicts</th>
<th>Input</th>
<th>Output</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Traitar</strong></td>
<td>67 classical microbial phenotypes (Gram stain, oxygen requirement, carbohydrate utilization, enzyme activity, biochemical tests, growth conditions)</td>
<td>MAG genomes</td>
<td>per-MAG trait calls → per-sample proportion / coverage-weighted prevalence</td>
</tr>
<tr class="even">
<td><strong>microTrait</strong></td>
<td>Hierarchical life-history traits (Resource Acquisition / Resource Use / Stress Tolerance; substrate uptake, degradation, assimilation, chemotrophy, phototrophy)</td>
<td>MAG genomes</td>
<td>per-MAG binary trait calls → per-sample proportion / coverage-weighted score</td>
</tr>
<tr class="odd">
<td><strong>dbCAN3</strong></td>
<td>CAZyme (carbohydrate-active enzyme) families (GH / GT / PL / CE / AA / CBM)</td>
<td>MAG genomes</td>
<td>per-MAG CAZyme counts → per-sample proportion / score / present-count</td>
</tr>
</tbody>
</table>
<p>All three tools share the same annotated-table format (<code>SID, profile_column, source, &lt;features...&gt;</code>), so the same downstream visualisation framework is reused.</p>
</section>
<section id="statistical-methods" class="level2">
<h2 class="anchored" data-anchor-id="statistical-methods">1.3 Statistical methods</h2>
<ul>
<li><strong>Aitchison distance</strong> (CLR + Euclidean) for compositional proportion data — NOT Bray-Curtis or UniFrac. Zeros are handled by multiplicative replacement (pseudocount = half the minimum positive value per row).</li>
<li><strong>PERMANOVA</strong> (<code>adonis2</code>, 999 permutations) preceded by a <strong>betadisper</strong> test for homogeneity of dispersion; PCoA ordination with 68% confidence ellipses.</li>
<li><strong>Kruskal-Wallis global test</strong> (not pairwise Wilcoxon) for the 6-group and 4-group comparisons, with BH-FDR correction.</li>
<li><strong>Effect sizes</strong>: max − min group median (or mean) per trait.</li>
<li><strong>dbCAN3 differential analysis</strong>: ALDEx2 (Monte Carlo CLR, 128 Dirichlet samples, Kruskal-Wallis test) when installed, with a plain Kruskal-Wallis + BH fallback.</li>
<li><strong>Targeted mucin modules</strong>: curated CAZyme families are collapsed into four biologically-motivated modules (mucin core / mucin extended / chitin / plant) to reduce the multiple-testing burden.</li>
</ul>
</section>
<section id="output-layout" class="level2">
<h2 class="anchored" data-anchor-id="output-layout">1.4 Output layout</h2>
<pre><code>01-Traitar/enhanced/Results/traitar_plot_02/       6-group figures + CSV tables
  traitar_4/                                        4-group (adenoma) figures + CSV tables
02-MicroTrait/results/microtrait-plot/              6-group figures + CSV tables
  plot-4/                                           4-group (adenoma) figures + CSV tables
04-dbcan3/results/dbcan3-plot-02/                  6-group figures + CSV tables
  plot-4/                                           4-group (adenoma) figures + CSV tables
  pairwise/                                         pairwise comparisons
04-dbcan3/results/dbcan3-plot-mucin/               mucin-module analysis
  dbcan3-4/                                         4-group (adenoma) figures + CSV tables</code></pre>
</section>
</section>
<section id="traitar" class="level1">
<h1>2. Traitar</h1>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">2.1 Overview</h2>
<p>Traitar (Weimann et al., 2016) predicts 67 classical microbial phenotypes from genome content. For each sample, the fraction of MAGs carrying each trait (proportion) and the coverage-weighted prevalence (fraction of the community carrying the trait) are computed. The analysis compares the 6 clinical groups and the 4-group adenoma follow-up subset.</p>
<p><strong>Key results (4-group adenoma subset):</strong></p>
<ul>
<li><strong>No trait is significant after BH-FDR correction.</strong> The strongest raw-p hit is <em>Acetate utilization</em> (Kruskal-Wallis p = 0.0099, padj = 0.652).</li>
<li>The largest between-group effect is <em>Trehalose utilization</em> (effect size 0.088, Recurrence_2 vs Non_recurrence_1).</li>
<li>PERMANOVA finds no multivariate separation: 6-group R² = 0.013, P = 0.448; 4-group R² = 0.012, P = 0.523. The 6-group betadisper test is marginally significant (P = 0.043), i.e.&nbsp;the groups differ slightly in dispersion, not location.</li>
</ul>
</section>
<section id="script" class="level2">
<h2 class="anchored" data-anchor-id="script">2.2 Script</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># targetc_traitar_plot_02.R — key functions</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Groups: N / Re1 / Re2 / Non1 / Non2 / CRC; 4-group adenoma subset</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>GROUP_LABELS <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"N"</span> <span class="ot">=</span> <span class="st">"Normal"</span>, <span class="st">"Re1"</span> <span class="ot">=</span> <span class="st">"Recurrence_1"</span>, <span class="st">"Re2"</span> <span class="ot">=</span> <span class="st">"Recurrence_2"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Non1"</span> <span class="ot">=</span> <span class="st">"Non_recurrence_1"</span>, <span class="st">"Non2"</span> <span class="ot">=</span> <span class="st">"Non_recurrence_2"</span>, <span class="st">"CRC"</span> <span class="ot">=</span> <span class="st">"CRC"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>GROUP_LEVELS <span class="ot">&lt;-</span> <span class="fu">unname</span>(GROUP_LABELS)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>FOUR_LEVELS  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Recurrence_1"</span>, <span class="st">"Recurrence_2"</span>, <span class="st">"Non_recurrence_1"</span>, <span class="st">"Non_recurrence_2"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># CLR transform with zero handling (multiplicative replacement via pseudocount)</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>clr_transform <span class="ot">&lt;-</span> <span class="cf">function</span>(mat) {</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  mat_out <span class="ot">&lt;-</span> mat</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_len</span>(<span class="fu">nrow</span>(mat_out))) {</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    row_vals <span class="ot">&lt;-</span> mat_out[i, ]</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    min_pos <span class="ot">&lt;-</span> <span class="fu">min</span>(row_vals[row_vals <span class="sc">&gt;</span> <span class="dv">0</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    mat_out[i, row_vals <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> min_pos <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  gm <span class="ot">&lt;-</span> <span class="fu">apply</span>(mat_out, <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">exp</span>(<span class="fu">mean</span>(<span class="fu">log</span>(x))))</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(mat_out <span class="sc">/</span> gm)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Aitchison PCoA + PERMANOVA + betadisper</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>make_pcoa <span class="ot">&lt;-</span> <span class="cf">function</span>(pcov_df, grp_lvls, colors, title_str, out_file) {</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> pcov_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Group)) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Group <span class="sc">%in%</span> grp_lvls) <span class="sc">%&gt;%</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Group =</span> <span class="fu">factor</span>(Group, <span class="at">levels =</span> grp_lvls))</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>  mat <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">all_of</span>(<span class="fu">c</span>(<span class="st">"row_id"</span>, trait_cols))) <span class="sc">%&gt;%</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">column_to_rownames</span>(<span class="st">"row_id"</span>) <span class="sc">%&gt;%</span> <span class="fu">as.matrix</span>()</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>  tv <span class="ot">&lt;-</span> <span class="fu">apply</span>(mat, <span class="dv">2</span>, var, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>  mat <span class="ot">&lt;-</span> mat[, tv <span class="sc">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>  clr_mat <span class="ot">&lt;-</span> <span class="fu">clr_transform</span>(mat)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>  dist_mat <span class="ot">&lt;-</span> <span class="fu">dist</span>(clr_mat, <span class="at">method =</span> <span class="st">"euclidean"</span>)   <span class="co"># Aitchison distance</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>  pcoa_res <span class="ot">&lt;-</span> <span class="fu">cmdscale</span>(dist_mat, <span class="at">k =</span> <span class="fu">min</span>(<span class="dv">2</span>, <span class="fu">nrow</span>(clr_mat) <span class="sc">-</span> <span class="dv">1</span>), <span class="at">eig =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>  pos_eig <span class="ot">&lt;-</span> pcoa_res<span class="sc">$</span>eig[pcoa_res<span class="sc">$</span>eig <span class="sc">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>  var_exp <span class="ot">&lt;-</span> <span class="fu">round</span>(pos_eig[<span class="dv">1</span><span class="sc">:</span><span class="fu">min</span>(<span class="dv">2</span>, <span class="fu">length</span>(pos_eig))] <span class="sc">/</span> <span class="fu">sum</span>(pos_eig) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>  scores <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(pcoa_res<span class="sc">$</span>points)</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>(scores) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PCoA1"</span>, <span class="st">"PCoA2"</span>)[<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(scores)]</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>  scores<span class="sc">$</span>row_id <span class="ot">&lt;-</span> <span class="fu">rownames</span>(scores)</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>  scores <span class="ot">&lt;-</span> scores <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(df <span class="sc">%&gt;%</span> <span class="fu">select</span>(row_id, Group) <span class="sc">%&gt;%</span> <span class="fu">distinct</span>(), <span class="at">by =</span> <span class="st">"row_id"</span>)</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>  scores<span class="sc">$</span>Group <span class="ot">&lt;-</span> <span class="fu">factor</span>(scores<span class="sc">$</span>Group, <span class="at">levels =</span> grp_lvls)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>  grp_vec <span class="ot">&lt;-</span> scores<span class="sc">$</span>Group[<span class="fu">match</span>(<span class="fu">labels</span>(dist_mat), scores<span class="sc">$</span>row_id)]</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>  adonis_res <span class="ot">&lt;-</span> <span class="fu">adonis2</span>(dist_mat <span class="sc">~</span> grp_vec, <span class="at">permutations =</span> <span class="dv">999</span>)</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>  p_val <span class="ot">&lt;-</span> adonis_res<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>]</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>  r2 <span class="ot">&lt;-</span> <span class="fu">round</span>(adonis_res<span class="sc">$</span>R2[<span class="dv">1</span>], <span class="dv">3</span>)</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>  beta_disp <span class="ot">&lt;-</span> <span class="fu">betadisper</span>(dist_mat, grp_vec)</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>  beta_p <span class="ot">&lt;-</span> <span class="fu">anova</span>(beta_disp)<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>]</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>  centroids <span class="ot">&lt;-</span> scores <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Group) <span class="sc">%&gt;%</span></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">PCoA1 =</span> <span class="fu">mean</span>(PCoA1), <span class="at">PCoA2 =</span> <span class="fu">mean</span>(PCoA2), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>  subtitle <span class="ot">&lt;-</span> <span class="fu">bquote</span>(<span class="st">"PERMANOVA: "</span> <span class="sc">~</span> R<span class="sc">^</span><span class="dv">2</span> <span class="sc">==</span> .(r2) <span class="sc">~</span> <span class="st">", p"</span> <span class="sc">==</span> .(<span class="fu">format.pval</span>(p_val, <span class="at">digits =</span> <span class="dv">3</span>)) <span class="sc">~</span></span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | Dispersion p"</span> <span class="sc">==</span> .(<span class="fu">format.pval</span>(beta_p, <span class="at">digits =</span> <span class="dv">3</span>)))</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(scores, <span class="fu">aes</span>(<span class="at">x =</span> PCoA1, <span class="at">y =</span> PCoA2, <span class="at">color =</span> Group, <span class="at">fill =</span> Group)) <span class="sc">+</span></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">data =</span> centroids, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">stroke =</span> <span class="fl">1.5</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_ellipse</span>(<span class="at">level =</span> <span class="fl">0.68</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> colors[grp_lvls]) <span class="sc">+</span></span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> colors[grp_lvls]) <span class="sc">+</span></span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> title_str, <span class="at">subtitle =</span> subtitle,</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="fu">sprintf</span>(<span class="st">"PCoA1 (%.1f%%)"</span>, var_exp[<span class="dv">1</span>]),</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="fu">sprintf</span>(<span class="st">"PCoA2 (%.1f%%)"</span>, var_exp[<span class="dv">2</span>])) <span class="sc">+</span></span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_nature</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggsave</span>(out_file, p, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">6</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">scores =</span> scores, <span class="at">adonis_r2 =</span> r2, <span class="at">adonis_p =</span> p_val, <span class="at">betadisper_p =</span> beta_p)</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a><span class="co"># Kruskal-Wallis global test + volcano</span></span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>make_kw_volcano <span class="ot">&lt;-</span> <span class="cf">function</span>(long_df, title_str, out_file) {</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a>  kw_res <span class="ot">&lt;-</span> long_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Group)) <span class="sc">%&gt;%</span></span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(trait) <span class="sc">%&gt;%</span></span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">kw_stat =</span> <span class="fu">kruskal.test</span>(wmean <span class="sc">~</span> Group)<span class="sc">$</span>statistic,</span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a>              <span class="at">kw_pval =</span> <span class="fu">kruskal.test</span>(wmean <span class="sc">~</span> Group)<span class="sc">$</span>p.value, <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">kw_padj =</span> <span class="fu">p.adjust</span>(kw_pval, <span class="at">method =</span> <span class="st">"BH"</span>),</span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a>           <span class="at">neg_log10_padj =</span> <span class="sc">-</span><span class="fu">log10</span>(kw_padj)) <span class="sc">%&gt;%</span></span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a>    <span class="fu">left_join</span>(trait_cat_df, <span class="at">by =</span> <span class="st">"trait"</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(kw_padj)</span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a>  grp_med <span class="ot">&lt;-</span> long_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Group)) <span class="sc">%&gt;%</span></span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(trait, Group) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">med =</span> <span class="fu">median</span>(wmean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a>  eff <span class="ot">&lt;-</span> grp_med <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(trait) <span class="sc">%&gt;%</span></span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">effect_size =</span> <span class="fu">max</span>(med) <span class="sc">-</span> <span class="fu">min</span>(med), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a>  kw_volc <span class="ot">&lt;-</span> kw_res <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(eff, <span class="at">by =</span> <span class="st">"trait"</span>)</span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a>  sig <span class="ot">&lt;-</span> kw_volc <span class="sc">%&gt;%</span> <span class="fu">filter</span>(kw_padj <span class="sc">&lt;</span> <span class="fl">0.05</span>) <span class="sc">%&gt;%</span> <span class="fu">slice_max</span>(<span class="at">order_by =</span> neg_log10_padj, <span class="at">n =</span> <span class="dv">15</span>)</span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(kw_volc, <span class="fu">aes</span>(<span class="at">x =</span> effect_size, <span class="at">y =</span> neg_log10_padj, <span class="at">color =</span> category)) <span class="sc">+</span></span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="sc">-</span><span class="fu">log10</span>(<span class="fl">0.05</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"grey40"</span>, <span class="at">linewidth =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> CAT_COLORS) <span class="sc">+</span></span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a>    ggrepel<span class="sc">::</span><span class="fu">geom_text_repel</span>(<span class="at">data =</span> sig, <span class="fu">aes</span>(<span class="at">label =</span> trait), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">max.overlaps =</span> <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> title_str, <span class="at">x =</span> <span class="st">"Effect Size (max - min group median)"</span>,</span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="fu">expression</span>(<span class="sc">-</span>log[<span class="dv">10</span>](adj.<span class="sc">~</span>p)), <span class="at">color =</span> <span class="st">"Category"</span>) <span class="sc">+</span></span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_nature</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggsave</span>(out_file, p, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="fl">5.5</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a>  kw_res</span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">2.3 Results</h2>
<p><strong>Kruskal-Wallis, 4-group adenoma subset (top raw-p traits):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Trait</th>
<th>Category</th>
<th>kw_stat</th>
<th>p</th>
<th>padj</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Acetate utilization</td>
<td>Biochemical tests</td>
<td>11.37</td>
<td>0.0099</td>
<td>0.652</td>
</tr>
<tr class="even">
<td>Anaerobe</td>
<td>Oxygen requirement</td>
<td>6.16</td>
<td>0.104</td>
<td>0.913</td>
</tr>
<tr class="odd">
<td>(all other traits)</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>0.913</td>
</tr>
</tbody>
</table>
<p><strong>Kruskal-Wallis, 6 groups (top raw-p traits):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Trait</th>
<th>Category</th>
<th>kw_stat</th>
<th>p</th>
<th>padj</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Beta hemolysis</td>
<td>Biochemical tests</td>
<td>14.92</td>
<td>0.0107</td>
<td>0.708</td>
</tr>
<tr class="even">
<td>Acetate utilization</td>
<td>Biochemical tests</td>
<td>12.28</td>
<td>0.0311</td>
<td>0.878</td>
</tr>
<tr class="odd">
<td>Anaerobe</td>
<td>Oxygen requirement</td>
<td>11.31</td>
<td>0.0457</td>
<td>0.878</td>
</tr>
</tbody>
</table>
<p><strong>Effect sizes, 4-group (max − min group mean):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Trait</th>
<th>Effect size</th>
<th>Group max</th>
<th>Group min</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Trehalose</td>
<td>0.088</td>
<td>Recurrence_2</td>
<td>Non_recurrence_1</td>
</tr>
<tr class="even">
<td>Alkaline phosphatase</td>
<td>0.085</td>
<td>Recurrence_2</td>
<td>Non_recurrence_1</td>
</tr>
<tr class="odd">
<td>Bile-susceptible</td>
<td>0.081</td>
<td>Recurrence_1</td>
<td>Non_recurrence_2</td>
</tr>
</tbody>
</table>
<p><strong>PERMANOVA + betadisper:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Comparison</th>
<th>n</th>
<th>R²</th>
<th>PERMANOVA p</th>
<th>Betadisper p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>All 6 groups</td>
<td>382</td>
<td>0.013</td>
<td>0.448</td>
<td>0.043</td>
</tr>
<tr class="even">
<td>Adenoma follow-up (4 groups)</td>
<td>236</td>
<td>0.012</td>
<td>0.523</td>
<td>0.712</td>
</tr>
</tbody>
</table>
</section>
<section id="figures" class="level2">
<h2 class="anchored" data-anchor-id="figures">2.4 Figures</h2>
<p><a href="Figure/traitar/fig1_phenotype_heatmap.png" target="_blank"> <img src="Figure/traitar/fig1_phenotype_heatmap.png" id="fig-tr-heatmap" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="Traitar phenotype heatmap"> </a></p>
<p><strong>Figure 1.</strong> Top-variable phenotype heatmap (4-group adenoma subset, row-scaled proportions). Columns are samples annotated by group; rows are the 40 most variable traits annotated by category. No obvious group-specific block structure is visible.</p>
<p><a href="Figure/traitar/fig5_pcoa_phenotype.png" target="_blank"> <img src="Figure/traitar/fig5_pcoa_phenotype.png" id="fig-tr-pcoa" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="Traitar Aitchison PCoA"> </a></p>
<p><strong>Figure 2.</strong> Aitchison PCoA of the 4-group adenoma subset (CLR + Euclidean distance). PERMANOVA R² = 0.012, P = 0.523; dispersion P = 0.712. The four groups overlap almost completely.</p>
<p><a href="Figure/traitar/fig6_differential_phenotype.png" target="_blank"> <img src="Figure/traitar/fig6_differential_phenotype.png" id="fig-tr-volc" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="Traitar differential volcano"> </a></p>
<p><strong>Figure 3.</strong> Differential-phenotype volcano (Kruskal-Wallis, x = effect size, y = −log10 adjusted p). No trait crosses the FDR &lt; 0.05 threshold.</p>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">2.5 Interpretation</h2>
<ol type="1">
<li><strong>No Traitar phenotype differs significantly between the four adenoma follow-up groups</strong> (best raw p = 0.0099 for Acetate utilization, padj = 0.652). The predicted classical phenotypes of the gut microbiome are essentially stable across recurrence status and sampling time.</li>
<li>The largest effect sizes (Trehalose, Alkaline phosphatase, Bile-susceptible) are small (0.08–0.09 on a 0–1 prevalence scale) and point in no consistent biological direction.</li>
<li>The marginally significant 6-group betadisper (P = 0.043) reflects slightly heterogeneous dispersion (the CRC group is the most distinct), not a location shift — PERMANOVA itself is non-significant.</li>
</ol>
</section>
</section>
<section id="microtrait" class="level1">
<h1>3. microTrait</h1>
<section id="overview-1" class="level2">
<h2 class="anchored" data-anchor-id="overview-1">3.1 Overview</h2>
<p>microTrait (Karaoz &amp; Brodie, 2022) predicts hierarchical life-history traits from genome content. Traits are organised as <code>Top:Mid:Leaf</code> (e.g. <code>Resource Acquisition:Substrate uptake:polysaccharide transport</code>). For each sample, the coverage-weighted score (sum of MAG-level binary calls weighted by coverage) is used for per-trait tests, and the compositional proportion for multivariate analysis.</p>
<p><strong>Key results (4-group adenoma subset):</strong></p>
<ul>
<li><strong>No trait is significant after BH-FDR correction</strong> (all padj = 0.357). The strongest raw-p hits are <em>polysaccharide transport</em> (p = 0.0115), <em>nucleotide transport</em> (p = 0.0192) and <em>lipid precursor transport</em> (p = 0.0220).</li>
<li>The largest effect size is <em>protein degradation</em> (5939.6, Non_recurrence_2 vs Recurrence_1) — a large absolute score difference driven by coverage.</li>
<li>PERMANOVA: 6-group R² = 0.015, P = 0.201; 4-group R² = 0.014, P = 0.266. No multivariate separation.</li>
</ul>
</section>
<section id="script-1" class="level2">
<h2 class="anchored" data-anchor-id="script-1">3.2 Script</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># targetc_micotrait_plot.R — key functions</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># microTrait traits are hierarchical, colon-separated: "Top:Mid:Leaf:..."</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>parse_trait_categories <span class="ot">&lt;-</span> <span class="cf">function</span>(trait_names) {</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(trait_names, <span class="cf">function</span>(t) {</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    parts <span class="ot">&lt;-</span> <span class="fu">strsplit</span>(t, <span class="st">":"</span>, <span class="at">fixed =</span> <span class="cn">TRUE</span>)[[<span class="dv">1</span>]]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">trait =</span> t,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">super_category =</span> parts[<span class="dv">1</span>],</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">category =</span> <span class="cf">if</span> (<span class="fu">length</span>(parts) <span class="sc">&gt;=</span> <span class="dv">2</span>) <span class="fu">paste</span>(parts[<span class="dv">1</span>], parts[<span class="dv">2</span>], <span class="at">sep =</span> <span class="st">" &gt; "</span>) <span class="cf">else</span> parts[<span class="dv">1</span>],</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  }))</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co"># CLR transform with zero handling (multiplicative replacement via pseudocount)</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>clr_transform <span class="ot">&lt;-</span> <span class="cf">function</span>(mat) {</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>  mat_out <span class="ot">&lt;-</span> mat</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_len</span>(<span class="fu">nrow</span>(mat_out))) {</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    row_vals <span class="ot">&lt;-</span> mat_out[i, ]</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    min_pos <span class="ot">&lt;-</span> <span class="fu">min</span>(row_vals[row_vals <span class="sc">&gt;</span> <span class="dv">0</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">is.finite</span>(min_pos)) mat_out[i, row_vals <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> min_pos <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>  gm <span class="ot">&lt;-</span> <span class="fu">apply</span>(mat_out, <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">exp</span>(<span class="fu">mean</span>(<span class="fu">log</span>(x))))</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(mat_out <span class="sc">/</span> gm)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Aitchison PCoA + PERMANOVA + betadisper (same framework as Traitar)</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>make_pcoa <span class="ot">&lt;-</span> <span class="cf">function</span>(pcov_df, grp_lvls, colors, title_str, out_file) {</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> pcov_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Group <span class="sc">%in%</span> grp_lvls) <span class="sc">%&gt;%</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Group =</span> <span class="fu">factor</span>(Group, <span class="at">levels =</span> grp_lvls))</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>  mat <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">all_of</span>(<span class="fu">c</span>(<span class="st">"row_id"</span>, trait_cols))) <span class="sc">%&gt;%</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">column_to_rownames</span>(<span class="st">"row_id"</span>) <span class="sc">%&gt;%</span> <span class="fu">as.matrix</span>()</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>  tv <span class="ot">&lt;-</span> <span class="fu">apply</span>(mat, <span class="dv">2</span>, var, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>  mat <span class="ot">&lt;-</span> mat[, tv <span class="sc">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>  clr_mat <span class="ot">&lt;-</span> <span class="fu">clr_transform</span>(mat)</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>  dist_mat <span class="ot">&lt;-</span> <span class="fu">dist</span>(clr_mat, <span class="at">method =</span> <span class="st">"euclidean"</span>)   <span class="co"># Aitchison distance</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>  pcoa_res <span class="ot">&lt;-</span> <span class="fu">cmdscale</span>(dist_mat, <span class="at">k =</span> <span class="fu">min</span>(<span class="dv">2</span>, <span class="fu">nrow</span>(clr_mat) <span class="sc">-</span> <span class="dv">1</span>), <span class="at">eig =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>  pos_eig <span class="ot">&lt;-</span> pcoa_res<span class="sc">$</span>eig[pcoa_res<span class="sc">$</span>eig <span class="sc">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>  var_exp <span class="ot">&lt;-</span> <span class="fu">round</span>(pos_eig[<span class="dv">1</span><span class="sc">:</span><span class="fu">min</span>(<span class="dv">2</span>, <span class="fu">length</span>(pos_eig))] <span class="sc">/</span> <span class="fu">sum</span>(pos_eig) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>  scores <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(pcoa_res<span class="sc">$</span>points)</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>(scores) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PCoA1"</span>, <span class="st">"PCoA2"</span>)[<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(scores)]</span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>  scores<span class="sc">$</span>row_id <span class="ot">&lt;-</span> <span class="fu">rownames</span>(scores)</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>  scores <span class="ot">&lt;-</span> scores <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(df <span class="sc">%&gt;%</span> <span class="fu">select</span>(row_id, Group) <span class="sc">%&gt;%</span> <span class="fu">distinct</span>(), <span class="at">by =</span> <span class="st">"row_id"</span>)</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>  scores<span class="sc">$</span>Group <span class="ot">&lt;-</span> <span class="fu">factor</span>(scores<span class="sc">$</span>Group, <span class="at">levels =</span> grp_lvls)</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>  grp_vec <span class="ot">&lt;-</span> scores<span class="sc">$</span>Group[<span class="fu">match</span>(<span class="fu">labels</span>(dist_mat), scores<span class="sc">$</span>row_id)]</span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>  adonis_res <span class="ot">&lt;-</span> <span class="fu">adonis2</span>(dist_mat <span class="sc">~</span> grp_vec, <span class="at">permutations =</span> <span class="dv">999</span>)</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>  p_val <span class="ot">&lt;-</span> adonis_res<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>]</span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>  r2 <span class="ot">&lt;-</span> <span class="fu">round</span>(adonis_res<span class="sc">$</span>R2[<span class="dv">1</span>], <span class="dv">3</span>)</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>  beta_disp <span class="ot">&lt;-</span> <span class="fu">betadisper</span>(dist_mat, grp_vec)</span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>  beta_p <span class="ot">&lt;-</span> <span class="fu">anova</span>(beta_disp)<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>]</span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>  centroids <span class="ot">&lt;-</span> scores <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Group) <span class="sc">%&gt;%</span></span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">PCoA1 =</span> <span class="fu">mean</span>(PCoA1), <span class="at">PCoA2 =</span> <span class="fu">mean</span>(PCoA2), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>  subtitle <span class="ot">&lt;-</span> <span class="fu">bquote</span>(<span class="st">"PERMANOVA: "</span> <span class="sc">~</span> R<span class="sc">^</span><span class="dv">2</span> <span class="sc">==</span> .(r2) <span class="sc">~</span> <span class="st">", p"</span> <span class="sc">==</span> .(<span class="fu">format.pval</span>(p_val, <span class="at">digits =</span> <span class="dv">3</span>)) <span class="sc">~</span></span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | Dispersion p"</span> <span class="sc">==</span> .(<span class="fu">format.pval</span>(beta_p, <span class="at">digits =</span> <span class="dv">3</span>)))</span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(scores, <span class="fu">aes</span>(<span class="at">x =</span> PCoA1, <span class="at">y =</span> PCoA2, <span class="at">color =</span> Group, <span class="at">fill =</span> Group)) <span class="sc">+</span></span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">data =</span> centroids, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">stroke =</span> <span class="fl">1.5</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_ellipse</span>(<span class="at">level =</span> <span class="fl">0.68</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> colors[grp_lvls]) <span class="sc">+</span></span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> colors[grp_lvls]) <span class="sc">+</span></span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> title_str, <span class="at">subtitle =</span> subtitle,</span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="fu">sprintf</span>(<span class="st">"PCoA1 (%.1f%%)"</span>, var_exp[<span class="dv">1</span>]),</span>
<span id="cb3-66"><a href="#cb3-66" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="fu">sprintf</span>(<span class="st">"PCoA2 (%.1f%%)"</span>, var_exp[<span class="dv">2</span>])) <span class="sc">+</span></span>
<span id="cb3-67"><a href="#cb3-67" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_nature</span>(<span class="at">base_size =</span> <span class="dv">15</span>)</span>
<span id="cb3-68"><a href="#cb3-68" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggsave</span>(out_file, p, <span class="at">width =</span> <span class="fl">7.5</span>, <span class="at">height =</span> <span class="fl">5.8</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span>
<span id="cb3-69"><a href="#cb3-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">scores =</span> scores, <span class="at">adonis_r2 =</span> r2, <span class="at">adonis_p =</span> p_val, <span class="at">betadisper_p =</span> beta_p)</span>
<span id="cb3-70"><a href="#cb3-70" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-71"><a href="#cb3-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-72"><a href="#cb3-72" aria-hidden="true" tabindex="-1"></a><span class="co"># Kruskal-Wallis global test + volcano (super-category coloured)</span></span>
<span id="cb3-73"><a href="#cb3-73" aria-hidden="true" tabindex="-1"></a>make_kw_volcano <span class="ot">&lt;-</span> <span class="cf">function</span>(long_df, title_str, out_file) {</span>
<span id="cb3-74"><a href="#cb3-74" aria-hidden="true" tabindex="-1"></a>  kw_res <span class="ot">&lt;-</span> long_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Group)) <span class="sc">%&gt;%</span></span>
<span id="cb3-75"><a href="#cb3-75" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(trait) <span class="sc">%&gt;%</span></span>
<span id="cb3-76"><a href="#cb3-76" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">kw_stat =</span> <span class="fu">kruskal.test</span>(wmean <span class="sc">~</span> Group)<span class="sc">$</span>statistic,</span>
<span id="cb3-77"><a href="#cb3-77" aria-hidden="true" tabindex="-1"></a>              <span class="at">kw_pval =</span> <span class="fu">kruskal.test</span>(wmean <span class="sc">~</span> Group)<span class="sc">$</span>p.value, <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-78"><a href="#cb3-78" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">kw_padj =</span> <span class="fu">p.adjust</span>(kw_pval, <span class="at">method =</span> <span class="st">"BH"</span>),</span>
<span id="cb3-79"><a href="#cb3-79" aria-hidden="true" tabindex="-1"></a>           <span class="at">neg_log10_padj =</span> <span class="sc">-</span><span class="fu">log10</span>(kw_padj)) <span class="sc">%&gt;%</span></span>
<span id="cb3-80"><a href="#cb3-80" aria-hidden="true" tabindex="-1"></a>    <span class="fu">left_join</span>(trait_cat_df, <span class="at">by =</span> <span class="st">"trait"</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(kw_padj)</span>
<span id="cb3-81"><a href="#cb3-81" aria-hidden="true" tabindex="-1"></a>  grp_med <span class="ot">&lt;-</span> long_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Group)) <span class="sc">%&gt;%</span></span>
<span id="cb3-82"><a href="#cb3-82" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(trait, Group) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">med =</span> <span class="fu">median</span>(wmean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb3-83"><a href="#cb3-83" aria-hidden="true" tabindex="-1"></a>  eff <span class="ot">&lt;-</span> grp_med <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(trait) <span class="sc">%&gt;%</span></span>
<span id="cb3-84"><a href="#cb3-84" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">effect_size =</span> <span class="fu">max</span>(med) <span class="sc">-</span> <span class="fu">min</span>(med), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb3-85"><a href="#cb3-85" aria-hidden="true" tabindex="-1"></a>  kw_volc <span class="ot">&lt;-</span> kw_res <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(eff, <span class="at">by =</span> <span class="st">"trait"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-86"><a href="#cb3-86" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">super_category =</span> <span class="fu">factor</span>(super_category, <span class="at">levels =</span> <span class="fu">names</span>(SUPER_COLORS)))</span>
<span id="cb3-87"><a href="#cb3-87" aria-hidden="true" tabindex="-1"></a>  sig <span class="ot">&lt;-</span> kw_volc <span class="sc">%&gt;%</span> <span class="fu">filter</span>(kw_padj <span class="sc">&lt;</span> <span class="fl">0.05</span>) <span class="sc">%&gt;%</span> <span class="fu">slice_max</span>(<span class="at">order_by =</span> neg_log10_padj, <span class="at">n =</span> <span class="dv">15</span>)</span>
<span id="cb3-88"><a href="#cb3-88" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(kw_volc, <span class="fu">aes</span>(<span class="at">x =</span> effect_size, <span class="at">y =</span> neg_log10_padj, <span class="at">color =</span> super_category)) <span class="sc">+</span></span>
<span id="cb3-89"><a href="#cb3-89" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">size =</span> <span class="fl">2.2</span>) <span class="sc">+</span></span>
<span id="cb3-90"><a href="#cb3-90" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="sc">-</span><span class="fu">log10</span>(<span class="fl">0.05</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"grey40"</span>, <span class="at">linewidth =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb3-91"><a href="#cb3-91" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> SUPER_COLORS, <span class="at">name =</span> <span class="st">"Super-category"</span>) <span class="sc">+</span></span>
<span id="cb3-92"><a href="#cb3-92" aria-hidden="true" tabindex="-1"></a>    ggrepel<span class="sc">::</span><span class="fu">geom_text_repel</span>(<span class="at">data =</span> sig, <span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">wrap_label</span>(<span class="fu">display_trait</span>(trait))),</span>
<span id="cb3-93"><a href="#cb3-93" aria-hidden="true" tabindex="-1"></a>      <span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">max.overlaps =</span> <span class="dv">25</span>) <span class="sc">+</span></span>
<span id="cb3-94"><a href="#cb3-94" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> title_str, <span class="at">x =</span> <span class="st">"Effect Size (max - min group median)"</span>,</span>
<span id="cb3-95"><a href="#cb3-95" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="fu">expression</span>(<span class="sc">-</span>log[<span class="dv">10</span>](adjusted <span class="sc">~</span> <span class="fu">italic</span>(p)))) <span class="sc">+</span></span>
<span id="cb3-96"><a href="#cb3-96" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_nature</span>(<span class="at">base_size =</span> <span class="dv">15</span>)</span>
<span id="cb3-97"><a href="#cb3-97" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggsave</span>(out_file, p, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="fl">5.8</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span>
<span id="cb3-98"><a href="#cb3-98" aria-hidden="true" tabindex="-1"></a>  kw_res <span class="sc">%&gt;%</span> <span class="fu">select</span>(trait, super_category, category, kw_stat, kw_pval, kw_padj)</span>
<span id="cb3-99"><a href="#cb3-99" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="results-1" class="level2">
<h2 class="anchored" data-anchor-id="results-1">3.3 Results</h2>
<p><strong>Kruskal-Wallis, 4-group adenoma subset (top raw-p traits):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 50%">
<col style="width: 9%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Trait</th>
<th>Super-category</th>
<th>p</th>
<th>padj</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Polysaccharide transport</td>
<td>Resource Acquisition</td>
<td>0.0115</td>
<td>0.357</td>
</tr>
<tr class="even">
<td>Nucleotide transport</td>
<td>Resource Acquisition</td>
<td>0.0192</td>
<td>0.357</td>
</tr>
<tr class="odd">
<td>Lipid precursor transport</td>
<td>Resource Acquisition</td>
<td>0.0220</td>
<td>0.357</td>
</tr>
<tr class="even">
<td>Thiosulfate oxidation</td>
<td>Resource Use</td>
<td>0.0283</td>
<td>0.357</td>
</tr>
<tr class="odd">
<td>ETC complex III</td>
<td>Resource Use</td>
<td>0.0283</td>
<td>0.357</td>
</tr>
<tr class="even">
<td>Oxygen sensing two-component systems</td>
<td>Stress Tolerance</td>
<td>0.0283</td>
<td>0.357</td>
</tr>
</tbody>
</table>
<p><strong>Kruskal-Wallis, 6 groups (top raw-p traits):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 50%">
<col style="width: 9%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Trait</th>
<th>Super-category</th>
<th>p</th>
<th>padj</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Assimilatory sulfate reduction</td>
<td>Resource Acquisition</td>
<td>0.0241</td>
<td>0.169</td>
</tr>
<tr class="even">
<td>Formaldehyde assimilation (serine)</td>
<td>Resource Acquisition</td>
<td>0.0360</td>
<td>0.169</td>
</tr>
<tr class="odd">
<td>Chitin breakdown</td>
<td>Resource Acquisition</td>
<td>0.0383</td>
<td>0.169</td>
</tr>
<tr class="even">
<td>EMP pathway</td>
<td>Resource Acquisition</td>
<td>0.0401</td>
<td>0.169</td>
</tr>
</tbody>
</table>
<p><strong>Effect sizes, 4-group (max − min group mean):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 29%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Trait</th>
<th>Effect size</th>
<th>Group max</th>
<th>Group min</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Protein degradation</td>
<td>5939.6</td>
<td>Non_recurrence_2</td>
<td>Recurrence_1</td>
</tr>
<tr class="even">
<td>Free amino acids transport</td>
<td>3184.3</td>
<td>Non_recurrence_2</td>
<td>Recurrence_1</td>
</tr>
<tr class="odd">
<td>Heat shock proteins</td>
<td>1249.7</td>
<td>Non_recurrence_2</td>
<td>Recurrence_1</td>
</tr>
<tr class="even">
<td>Xylan/heteroxylan breakdown</td>
<td>1219.9</td>
<td>Non_recurrence_2</td>
<td>Recurrence_1</td>
</tr>
</tbody>
</table>
<p><strong>PERMANOVA + betadisper:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Comparison</th>
<th>n</th>
<th>R²</th>
<th>PERMANOVA p</th>
<th>Betadisper p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>All 6 groups</td>
<td>382</td>
<td>0.015</td>
<td>0.201</td>
<td>0.579</td>
</tr>
<tr class="even">
<td>Adenoma follow-up (4 groups)</td>
<td>236</td>
<td>0.014</td>
<td>0.266</td>
<td>0.927</td>
</tr>
</tbody>
</table>
</section>
<section id="figures-1" class="level2">
<h2 class="anchored" data-anchor-id="figures-1">3.4 Figures</h2>
<p><a href="Figure/microtrait/fig5_pcoa_phenotype.png" target="_blank"> <img src="Figure/microtrait/fig5_pcoa_phenotype.png" id="fig-mt-pcoa" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="microTrait Aitchison PCoA"> </a></p>
<p><strong>Figure 4.</strong> Aitchison PCoA of the 4-group adenoma subset. PERMANOVA R² = 0.014, P = 0.266; dispersion P = 0.927. The four groups overlap almost completely.</p>
<p><a href="Figure/microtrait/fig6_differential_phenotype.png" target="_blank"> <img src="Figure/microtrait/fig6_differential_phenotype.png" id="fig-mt-volc" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="microTrait differential volcano"> </a></p>
<p><strong>Figure 5.</strong> Differential-trait volcano (Kruskal-Wallis, coloured by super-category). No trait crosses the FDR &lt; 0.05 threshold.</p>
<p><a href="Figure/microtrait/fig3_key_traits_boxplots.png" target="_blank"> <img src="Figure/microtrait/fig3_key_traits_boxplots.png" id="fig-mt-keybox" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="microTrait key traits boxplots"> </a></p>
<p><strong>Figure 6.</strong> Most-variable trait boxplots (top 12 by effect size) with Kruskal-Wallis labels. None are significant.</p>
</section>
<section id="interpretation-1" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-1">3.5 Interpretation</h2>
<ol type="1">
<li><strong>No microTrait trait differs significantly between the four adenoma follow-up groups</strong> (best raw p = 0.0115 for polysaccharide transport, padj = 0.357). The predicted life-history traits of the gut microbiome are stable across recurrence status and sampling time.</li>
<li>The top raw-p candidates (polysaccharide / nucleotide / lipid precursor transport, thiosulfate oxidation) are all <em>Resource Acquisition / Resource Use</em> traits — i.e.&nbsp;substrate-uptake and energy-metabolism capacity — but none survive correction.</li>
<li>The large effect sizes (protein degradation, free amino acid transport) are driven by coverage weighting and are not statistically significant; they reflect the Non_recurrence_2 group’s slightly higher MAG coverage, not a robust biological signal.</li>
</ol>
</section>
</section>
<section id="dbcan3" class="level1">
<h1>4. dbCAN3</h1>
<section id="overview-2" class="level2">
<h2 class="anchored" data-anchor-id="overview-2">4.1 Overview</h2>
<p>dbCAN3 (Zheng et al., 2023) annotates carbohydrate-active enzymes (CAZymes) in MAG genomes. CAZyme families are grouped into classes (GH, GT, PL, CE, AA, CBM). For each sample, the proportion of MAGs carrying each family (compositional) and the coverage-weighted score are computed. The analysis compares the 6 clinical groups and the 4-group adenoma follow-up subset (n = 236, 59 per group).</p>
<p><strong>Key results (4-group adenoma subset):</strong></p>
<ul>
<li><strong>No CAZyme family is significant after BH-FDR correction</strong> (all FDR = 0.955). The strongest raw-p hits are <em>CBM27</em> (p = 0.0040), <em>GH125</em> (p = 0.0062), <em>GH26</em> (p = 0.0104) and <em>GH6</em> (p = 0.0152).</li>
<li>PERMANOVA: R² = 0.0124, P = 0.545; dispersion P = 0.224. No multivariate separation.</li>
</ul>
</section>
<section id="script-2" class="level2">
<h2 class="anchored" data-anchor-id="script-2">4.2 Script</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># targetc_dbcan3_plot_02.R — key functions</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># CAZyme class from family name (e.g. "GH29" -&gt; "GH")</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>cazyme_class <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  cls <span class="ot">&lt;-</span> <span class="fu">sub</span>(<span class="st">"^([A-Z]+).*$"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">1"</span>, <span class="fu">as.character</span>(x))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  cls[<span class="sc">!</span>cls <span class="sc">%in%</span> <span class="fu">names</span>(CLASS_COLORS)] <span class="ot">&lt;-</span> <span class="st">"Other"</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>(cls, <span class="at">levels =</span> <span class="fu">names</span>(CLASS_COLORS))</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># CLR transform with zero handling (multiplicative replacement via pseudocount)</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>clr_transform <span class="ot">&lt;-</span> <span class="cf">function</span>(mat) {</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  mat[<span class="fu">is.na</span>(mat)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  pos <span class="ot">&lt;-</span> mat[mat <span class="sc">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  delta <span class="ot">&lt;-</span> <span class="cf">if</span> (<span class="fu">length</span>(pos) <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="fu">min</span>(pos) <span class="sc">/</span> <span class="dv">2</span> <span class="cf">else</span> <span class="fl">0.5</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  mat[mat <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> delta</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t</span>(<span class="fu">apply</span>(mat, <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">log</span>(x) <span class="sc">-</span> <span class="fu">mean</span>(<span class="fu">log</span>(x))))</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Aitchison PCoA + PERMANOVA + betadisper</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>run_beta <span class="ot">&lt;-</span> <span class="cf">function</span>(prop_wide, group_levels) {</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>  fams <span class="ot">&lt;-</span> <span class="fu">get_family_cols</span>(prop_wide)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  dat <span class="ot">&lt;-</span> prop_wide <span class="sc">%&gt;%</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Group)) <span class="sc">%&gt;%</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Group =</span> <span class="fu">factor</span>(Group, <span class="at">levels =</span> group_levels))</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>  mat <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(dat[, fams, <span class="at">drop =</span> <span class="cn">FALSE</span>])</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames</span>(mat) <span class="ot">&lt;-</span> dat<span class="sc">$</span>sample_id</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>  clr <span class="ot">&lt;-</span> <span class="fu">clr_transform</span>(mat)</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> <span class="fu">dist</span>(clr, <span class="at">method =</span> <span class="st">"euclidean"</span>)          <span class="co"># Aitchison distance</span></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>  ad <span class="ot">&lt;-</span> <span class="fu">adonis2</span>(d <span class="sc">~</span> Group, <span class="at">data =</span> dat, <span class="at">permutations =</span> <span class="dv">999</span>)</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>  disp <span class="ot">&lt;-</span> <span class="fu">anova</span>(<span class="fu">betadisper</span>(d, dat<span class="sc">$</span>Group))</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>  pcoa <span class="ot">&lt;-</span> <span class="fu">cmdscale</span>(d, <span class="at">k =</span> <span class="dv">2</span>, <span class="at">eig =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>  eig <span class="ot">&lt;-</span> pcoa<span class="sc">$</span>eig[pcoa<span class="sc">$</span>eig <span class="sc">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>  var_explained <span class="ot">&lt;-</span> <span class="cf">if</span> (<span class="fu">length</span>(eig) <span class="sc">&gt;=</span> <span class="dv">2</span>) <span class="fu">round</span>(eig[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>] <span class="sc">/</span> <span class="fu">sum</span>(eig) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>                   <span class="cf">else</span> <span class="fu">c</span>(<span class="cn">NA_real_</span>, <span class="cn">NA_real_</span>)</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>  scores <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(pcoa<span class="sc">$</span>points)</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>(scores) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PCoA1"</span>, <span class="st">"PCoA2"</span>)</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>  scores<span class="sc">$</span>sample_id <span class="ot">&lt;-</span> <span class="fu">rownames</span>(scores)</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>  scores <span class="ot">&lt;-</span> scores <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(dat <span class="sc">%&gt;%</span> <span class="fu">select</span>(sample_id, Group), <span class="at">by =</span> <span class="st">"sample_id"</span>)</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">scores =</span> scores, <span class="at">var_explained =</span> var_explained,</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>       <span class="at">r2 =</span> ad<span class="sc">$</span>R2[<span class="dv">1</span>], <span class="at">p =</span> ad<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>], <span class="at">disp_p =</span> disp<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>])</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Differential analysis: ALDEx2 (Monte Carlo CLR) or Kruskal-Wallis + BH fallback</span></span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>differential_analysis <span class="ot">&lt;-</span> <span class="cf">function</span>(prop_long, count_wide, group_levels) {</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>  fams <span class="ot">&lt;-</span> <span class="fu">get_family_cols</span>(count_wide)</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a>  dat <span class="ot">&lt;-</span> count_wide <span class="sc">%&gt;%</span></span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Group)) <span class="sc">%&gt;%</span></span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Group =</span> <span class="fu">factor</span>(Group, <span class="at">levels =</span> group_levels))</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a>  present_fams <span class="ot">&lt;-</span> fams[<span class="fu">colSums</span>(dat[, fams, <span class="at">drop =</span> <span class="cn">FALSE</span>] <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a>  use_aldex <span class="ot">&lt;-</span> <span class="fu">requireNamespace</span>(<span class="st">"ALDEx2"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a>  res <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (use_aldex <span class="sc">&amp;&amp;</span> <span class="fu">length</span>(present_fams) <span class="sc">&gt;</span> <span class="dv">1</span>) {</span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a>    count_mat <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(dat[, present_fams, <span class="at">drop =</span> <span class="cn">FALSE</span>])</span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rownames</span>(count_mat) <span class="ot">&lt;-</span> dat<span class="sc">$</span>sample_id</span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a>    al <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(ALDEx2<span class="sc">::</span><span class="fu">aldex</span>(count_mat, dat<span class="sc">$</span>Group, <span class="at">mc.samples =</span> <span class="dv">128</span>,</span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">test =</span> <span class="st">"kw"</span>, <span class="at">effect =</span> <span class="cn">TRUE</span>, <span class="at">denom =</span> <span class="st">"all"</span>),</span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a>                   <span class="at">error =</span> <span class="cf">function</span>(e) e)</span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="sc">!</span><span class="fu">inherits</span>(al, <span class="st">"error"</span>)) {</span>
<span id="cb4-61"><a href="#cb4-61" aria-hidden="true" tabindex="-1"></a>      res <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">family =</span> <span class="fu">rownames</span>(al), <span class="at">p.value =</span> al<span class="sc">$</span>kw.ep,</span>
<span id="cb4-62"><a href="#cb4-62" aria-hidden="true" tabindex="-1"></a>                        <span class="at">FDR =</span> al<span class="sc">$</span>kw.eBH, <span class="at">aldex_effect =</span> al<span class="sc">$</span>effect,</span>
<span id="cb4-63"><a href="#cb4-63" aria-hidden="true" tabindex="-1"></a>                        <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb4-64"><a href="#cb4-64" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> use_aldex <span class="ot">&lt;-</span> <span class="cn">FALSE</span></span>
<span id="cb4-65"><a href="#cb4-65" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb4-66"><a href="#cb4-66" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span>use_aldex) {</span>
<span id="cb4-67"><a href="#cb4-67" aria-hidden="true" tabindex="-1"></a>    res <span class="ot">&lt;-</span> prop_long <span class="sc">%&gt;%</span></span>
<span id="cb4-68"><a href="#cb4-68" aria-hidden="true" tabindex="-1"></a>      <span class="fu">group_by</span>(family) <span class="sc">%&gt;%</span></span>
<span id="cb4-69"><a href="#cb4-69" aria-hidden="true" tabindex="-1"></a>      <span class="fu">summarise</span>(<span class="at">p.value =</span> <span class="fu">suppressWarnings</span>(<span class="fu">tryCatch</span>(</span>
<span id="cb4-70"><a href="#cb4-70" aria-hidden="true" tabindex="-1"></a>        <span class="fu">kruskal.test</span>(proportion, Group)<span class="sc">$</span>p.value, <span class="at">error =</span> <span class="cf">function</span>(e) <span class="cn">NA_real_</span>)),</span>
<span id="cb4-71"><a href="#cb4-71" aria-hidden="true" tabindex="-1"></a>        <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb4-72"><a href="#cb4-72" aria-hidden="true" tabindex="-1"></a>    res<span class="sc">$</span>FDR <span class="ot">&lt;-</span> <span class="cn">NA_real_</span></span>
<span id="cb4-73"><a href="#cb4-73" aria-hidden="true" tabindex="-1"></a>    idx <span class="ot">&lt;-</span> <span class="sc">!</span><span class="fu">is.na</span>(res<span class="sc">$</span>p.value)</span>
<span id="cb4-74"><a href="#cb4-74" aria-hidden="true" tabindex="-1"></a>    res<span class="sc">$</span>FDR[idx] <span class="ot">&lt;-</span> <span class="fu">p.adjust</span>(res<span class="sc">$</span>p.value[idx], <span class="at">method =</span> <span class="st">"BH"</span>)</span>
<span id="cb4-75"><a href="#cb4-75" aria-hidden="true" tabindex="-1"></a>    res<span class="sc">$</span>aldex_effect <span class="ot">&lt;-</span> <span class="cn">NA_real_</span></span>
<span id="cb4-76"><a href="#cb4-76" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb4-77"><a href="#cb4-77" aria-hidden="true" tabindex="-1"></a>  <span class="co"># effect size = range of group median proportions; log2FC = max/min median</span></span>
<span id="cb4-78"><a href="#cb4-78" aria-hidden="true" tabindex="-1"></a>  stats <span class="ot">&lt;-</span> prop_long <span class="sc">%&gt;%</span></span>
<span id="cb4-79"><a href="#cb4-79" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(family, Group) <span class="sc">%&gt;%</span></span>
<span id="cb4-80"><a href="#cb4-80" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">mean_prop =</span> <span class="fu">mean</span>(proportion, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb4-81"><a href="#cb4-81" aria-hidden="true" tabindex="-1"></a>              <span class="at">median_prop =</span> <span class="fu">median</span>(proportion, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb4-82"><a href="#cb4-82" aria-hidden="true" tabindex="-1"></a>  median_wide <span class="ot">&lt;-</span> stats <span class="sc">%&gt;%</span> <span class="fu">select</span>(family, Group, median_prop) <span class="sc">%&gt;%</span></span>
<span id="cb4-83"><a href="#cb4-83" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Group, <span class="at">values_from =</span> median_prop)</span>
<span id="cb4-84"><a href="#cb4-84" aria-hidden="true" tabindex="-1"></a>  median_mat <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(median_wide[, <span class="fu">setdiff</span>(<span class="fu">colnames</span>(median_wide), <span class="st">"family"</span>), <span class="at">drop =</span> <span class="cn">FALSE</span>])</span>
<span id="cb4-85"><a href="#cb4-85" aria-hidden="true" tabindex="-1"></a>  effect_size <span class="ot">&lt;-</span> <span class="fu">apply</span>(median_mat, <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">max</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">-</span> <span class="fu">min</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb4-86"><a href="#cb4-86" aria-hidden="true" tabindex="-1"></a>  log2fc <span class="ot">&lt;-</span> <span class="fu">log2</span>((<span class="fu">apply</span>(median_mat, <span class="dv">1</span>, max, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fl">1e-6</span>) <span class="sc">/</span></span>
<span id="cb4-87"><a href="#cb4-87" aria-hidden="true" tabindex="-1"></a>                 (<span class="fu">apply</span>(median_mat, <span class="dv">1</span>, min, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fl">1e-6</span>))</span>
<span id="cb4-88"><a href="#cb4-88" aria-hidden="true" tabindex="-1"></a>  res <span class="ot">&lt;-</span> res <span class="sc">%&gt;%</span></span>
<span id="cb4-89"><a href="#cb4-89" aria-hidden="true" tabindex="-1"></a>    <span class="fu">left_join</span>(<span class="fu">data.frame</span>(<span class="at">family =</span> median_wide<span class="sc">$</span>family, <span class="at">effect_size =</span> effect_size,</span>
<span id="cb4-90"><a href="#cb4-90" aria-hidden="true" tabindex="-1"></a>                         <span class="at">log2FC =</span> log2fc, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>), <span class="at">by =</span> <span class="st">"family"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-91"><a href="#cb4-91" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">class =</span> <span class="fu">cazyme_class</span>(family)) <span class="sc">%&gt;%</span></span>
<span id="cb4-92"><a href="#cb4-92" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(FDR, <span class="fu">desc</span>(<span class="fu">abs</span>(effect_size)))</span>
<span id="cb4-93"><a href="#cb4-93" aria-hidden="true" tabindex="-1"></a>  res</span>
<span id="cb4-94"><a href="#cb4-94" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="results-2" class="level2">
<h2 class="anchored" data-anchor-id="results-2">4.3 Results</h2>
<p><strong>Sample sizes (4-group adenoma subset):</strong> Recurrence_1 = 59, Recurrence_2 = 59, Non_recurrence_1 = 59, Non_recurrence_2 = 59 (n = 236).</p>
<p><strong>Differential analysis, 4-group (top raw-p families):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Family</th>
<th>Class</th>
<th>p</th>
<th>FDR</th>
<th>log2FC</th>
<th>Effect size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CBM27</td>
<td>CBM</td>
<td>0.0040</td>
<td>0.955</td>
<td>9.06</td>
<td>0.00053</td>
</tr>
<tr class="even">
<td>GH125</td>
<td>GH</td>
<td>0.0062</td>
<td>0.955</td>
<td>1.11</td>
<td>0.00136</td>
</tr>
<tr class="odd">
<td>GH26</td>
<td>GH</td>
<td>0.0104</td>
<td>0.955</td>
<td>0.98</td>
<td>0.00159</td>
</tr>
<tr class="even">
<td>GH6</td>
<td>GH</td>
<td>0.0152</td>
<td>0.955</td>
<td>0.87</td>
<td>0.00299</td>
</tr>
<tr class="odd">
<td>CBM23</td>
<td>CBM</td>
<td>0.0095</td>
<td>0.955</td>
<td>9.65</td>
<td>0.00080</td>
</tr>
</tbody>
</table>
<p><strong>PERMANOVA + betadisper (4-group):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Method</th>
<th>R²</th>
<th>PERMANOVA p</th>
<th>Dispersion p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aitchison PCoA (CLR + Euclidean)</td>
<td>0.0124</td>
<td>0.545</td>
<td>0.224</td>
</tr>
</tbody>
</table>
</section>
<section id="figures-2" class="level2">
<h2 class="anchored" data-anchor-id="figures-2">4.4 Figures</h2>
<p><a href="Figure/dbcan3/fig1_aitchison_pcoa.png" target="_blank"> <img src="Figure/dbcan3/fig1_aitchison_pcoa.png" id="fig-db-pcoa" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="dbCAN3 Aitchison PCoA"> </a></p>
<p><strong>Figure 7.</strong> Aitchison PCoA of the 4-group adenoma subset (CLR + Euclidean distance). PERMANOVA R² = 0.0124, P = 0.545; dispersion P = 0.224. The four groups overlap almost completely.</p>
<p><a href="Figure/dbcan3/fig2_class_stacked_bar.png" target="_blank"> <img src="Figure/dbcan3/fig2_class_stacked_bar.png" id="fig-db-class" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="dbCAN3 class stacked bar"> </a></p>
<p><strong>Figure 8.</strong> CAZyme class composition (relative stacked bar: GH / GT / PL / CE / AA / CBM). Glycoside hydrolases dominate; the composition is stable across groups.</p>
<p><a href="Figure/dbcan3/fig3_gh_pl_violin.png" target="_blank"> <img src="Figure/dbcan3/fig3_gh_pl_violin.png" id="fig-db-ghpl" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="dbCAN3 GH/PL violin"> </a></p>
<p><strong>Figure 9.</strong> GH and PL family proportion violins by group. No significant differences.</p>
<p><a href="Figure/dbcan3/fig4_differential_volcano.png" target="_blank"> <img src="Figure/dbcan3/fig4_differential_volcano.png" id="fig-db-volc" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="dbCAN3 differential volcano"> </a></p>
<p><strong>Figure 10.</strong> Differential-CAZyme volcano (x = effect size, y = −log10 FDR). No family crosses the FDR &lt; 0.05 threshold; the top raw-p hits (CBM27, GH125, GH26, GH6) are labelled.</p>
<p><a href="Figure/dbcan3/fig6_prevalence_heatmap.png" target="_blank"> <img src="Figure/dbcan3/fig6_prevalence_heatmap.png" id="fig-db-prev" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="dbCAN3 prevalence heatmap"> </a></p>
<p><strong>Figure 11.</strong> CAZyme family prevalence heatmap (% of samples carrying each family per group). Prevalence is broadly similar across the four groups.</p>
<p><a href="Figure/dbcan3/fig7_top_family_boxplots.png" target="_blank"> <img src="Figure/dbcan3/fig7_top_family_boxplots.png" id="fig-db-topbox" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="dbCAN3 top family boxplots"> </a></p>
<p><strong>Figure 12.</strong> Top-variable CAZyme family boxplots with Kruskal-Wallis labels. None are significant.</p>
<p><a href="Figure/dbcan3/fig10_cazyme_family_dotplot.png" target="_blank"> <img src="Figure/dbcan3/fig10_cazyme_family_dotplot.png" id="fig-db-dot" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="dbCAN3 family dotplot"> </a></p>
<p><strong>Figure 13.</strong> All-CAZyme-family dot plot (mean proportion, faceted by class). The four groups track each other closely across all families.</p>
</section>
<section id="interpretation-2" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-2">4.5 Interpretation</h2>
<ol type="1">
<li><strong>No CAZyme family differs significantly between the four adenoma follow-up groups</strong> (best raw p = 0.0040 for CBM27, FDR = 0.955). The carbohydrate- active enzyme repertoire of the gut microbiome is stable across recurrence status and sampling time.</li>
<li>The top raw-p hits are carbohydrate-binding modules (CBM27, CBM23) and glycoside hydrolases (GH125, GH26, GH6) — i.e.&nbsp;hemicellulose/xylan- and cellulose-degrading machinery — but none survive correction.</li>
<li>The 6-group analysis (including Normal and CRC) is likewise non-significant (PERMANOVA R² = 0.0127, P = 0.597), confirming that CAZyme composition does not separate any clinical group.</li>
</ol>
</section>
</section>
<section id="dbcan3-mucin-modules" class="level1">
<h1>5. dbCAN3 mucin modules</h1>
<section id="overview-3" class="level2">
<h2 class="anchored" data-anchor-id="overview-3">5.1 Overview</h2>
<p>To reduce the multiple-testing burden of ~300 CAZyme families, curated families are collapsed into four biologically-motivated <strong>mucin / glycan modules</strong> (defined in <code>targetc_dbcan3_mucin_modules.R</code>):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Module</th>
<th>CAZyme families</th>
<th>Biological role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>mucin_core</td>
<td>GH29, GH95, GH33, GH109, GH16, GH136</td>
<td>Core mucin O-glycan degradation (fucose, sialic acid, GalNAc)</td>
</tr>
<tr class="even">
<td>mucin_ext</td>
<td>GH2, GH20, GH35, GH42, GH84, GH85, GH89, GH97, GH98, GH101, GH123, GH129, GH151</td>
<td>Extended mucin glycan degradation</td>
</tr>
<tr class="odd">
<td>chitin</td>
<td>GH18, GH19, GH20, GH23, CBM2, CBM5</td>
<td>Chitin utilization</td>
</tr>
<tr class="even">
<td>plant</td>
<td>GH5, GH26, GH28, GH43, GH51, GH53, GH67, GH78, GH105, GH115, CE1, CE4, CE12, PL1, PL3, PL4, PL9</td>
<td>Plant polysaccharide degradation</td>
</tr>
</tbody>
</table>
<p><strong>Key results (4-group adenoma subset):</strong></p>
<ul>
<li><strong>No module differs significantly</strong> (Kruskal-Wallis on module proportion: plant p = 0.178, chitin p = 0.396, mucin_ext p = 0.671, mucin_core p = 0.676).</li>
<li>PERMANOVA on the target families: R² = 0.0124, P = 0.503.</li>
<li>The strongest single-family hit is <em>GH26</em> (plant module, p = 0.0104, FDR = 0.418).</li>
</ul>
</section>
<section id="script-3" class="level2">
<h2 class="anchored" data-anchor-id="script-3">5.2 Script</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># targetc_dbcan3_mucin_modules.R — key definitions</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>MODULES <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mucin_core =</span> <span class="fu">c</span>(<span class="st">"GH29"</span>, <span class="st">"GH95"</span>, <span class="st">"GH33"</span>, <span class="st">"GH109"</span>, <span class="st">"GH16"</span>, <span class="st">"GH136"</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">mucin_ext  =</span> <span class="fu">c</span>(<span class="st">"GH2"</span>, <span class="st">"GH20"</span>, <span class="st">"GH35"</span>, <span class="st">"GH42"</span>, <span class="st">"GH84"</span>, <span class="st">"GH85"</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"GH89"</span>, <span class="st">"GH97"</span>, <span class="st">"GH98"</span>, <span class="st">"GH101"</span>, <span class="st">"GH123"</span>, <span class="st">"GH129"</span>, <span class="st">"GH151"</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">chitin =</span> <span class="fu">c</span>(<span class="st">"GH18"</span>, <span class="st">"GH19"</span>, <span class="st">"GH20"</span>, <span class="st">"GH23"</span>, <span class="st">"CBM2"</span>, <span class="st">"CBM5"</span>),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">plant  =</span> <span class="fu">c</span>(<span class="st">"GH5"</span>, <span class="st">"GH26"</span>, <span class="st">"GH28"</span>, <span class="st">"GH43"</span>, <span class="st">"GH51"</span>, <span class="st">"GH53"</span>, <span class="st">"GH67"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>             <span class="st">"GH78"</span>, <span class="st">"GH105"</span>, <span class="st">"GH115"</span>, <span class="st">"CE1"</span>, <span class="st">"CE4"</span>, <span class="st">"CE12"</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>             <span class="st">"PL1"</span>, <span class="st">"PL3"</span>, <span class="st">"PL4"</span>, <span class="st">"PL9"</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Per-sample module score = sum of the module's family proportions</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># (module proportion), and module richness = number of families present.</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Each module is then tested with Kruskal-Wallis across the 4 groups.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="results-3" class="level2">
<h2 class="anchored" data-anchor-id="results-3">5.3 Results</h2>
<p><strong>Module-level Kruskal-Wallis (4-group, on module proportion):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Module</th>
<th>mean proportion (Re1 → Non2)</th>
<th>KW p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Plant polysaccharide degradation</td>
<td>0.102 → 0.101</td>
<td>0.178</td>
</tr>
<tr class="even">
<td>Chitin utilization</td>
<td>0.028 → 0.029</td>
<td>0.396</td>
</tr>
<tr class="odd">
<td>Mucin degradation (extended)</td>
<td>0.050 → 0.051</td>
<td>0.671</td>
</tr>
<tr class="even">
<td>Mucin degradation (core)</td>
<td>0.029 → 0.031</td>
<td>0.676</td>
</tr>
</tbody>
</table>
<p><strong>PERMANOVA (4-group, target families):</strong> R² = 0.0124, P = 0.503, dispersion P = 0.343.</p>
<p><strong>Target-family differential (top raw-p):</strong> GH26 (plant) p = 0.0104, FDR = 0.418; GH53 (plant) p = 0.072; CE1 (plant) p = 0.106.</p>
</section>
<section id="figures-3" class="level2">
<h2 class="anchored" data-anchor-id="figures-3">5.4 Figures</h2>
<p><a href="Figure/dbcan3-mucin/figM1_mucin_module_boxplots.png" target="_blank"> <img src="Figure/dbcan3-mucin/figM1_mucin_module_boxplots.png" id="fig-muc-mod" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="Mucin module boxplots"> </a></p>
<p><strong>Figure 14.</strong> Mucin / glycan module boxplots (module proportion by group) with Kruskal-Wallis labels. No module is significant.</p>
<p><a href="Figure/dbcan3-mucin/figM5_mucin_clr_pcoa.png" target="_blank"> <img src="Figure/dbcan3-mucin/figM5_mucin_clr_pcoa.png" id="fig-muc-pcoa" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="Mucin CLR PCoA"> </a></p>
<p><strong>Figure 15.</strong> Aitchison PCoA of the mucin-target families. PERMANOVA R² = 0.0124, P = 0.503. The four groups overlap almost completely.</p>
<p><a href="Figure/dbcan3-mucin/figM2_mucin_family_volcano.png" target="_blank"> <img src="Figure/dbcan3-mucin/figM2_mucin_family_volcano.png" id="fig-muc-volc" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="Mucin family volcano"> </a></p>
<p><strong>Figure 16.</strong> Target-family differential volcano. GH26 (plant module) is the strongest raw-p hit but does not survive FDR correction.</p>
<p><a href="Figure/dbcan3-mucin/figM3_mucin_top_family_boxplots.png" target="_blank"> <img src="Figure/dbcan3-mucin/figM3_mucin_top_family_boxplots.png" id="fig-muc-topbox" class="img-fluid quarto-figure quarto-figure-center anchored" style="width:100.0%" alt="Mucin top family boxplots"> </a></p>
<p><strong>Figure 17.</strong> Top-variable mucin-target family boxplots. None are significant.</p>
</section>
<section id="interpretation-3" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-3">5.5 Interpretation</h2>
<ol type="1">
<li><strong>No mucin / glycan module differs significantly between the four adenoma follow-up groups.</strong> The mucin-degradation capacity of the gut microbiome (core and extended modules) is stable across recurrence status and sampling time.</li>
<li>The plant-polysaccharide module shows the strongest (still non-significant) trend (p = 0.178), driven mainly by GH26 (xylan/glucan backbone) — consistent with the dbCAN3 per-family result.</li>
<li>The module-level approach reduces the multiple-testing burden from ~300 families to 4 tests, but the effect sizes are simply too small to reach significance at n = 236.</li>
</ol>
</section>
</section>
<section id="overall-interpretation" class="level1">
<h1>6. Overall interpretation</h1>
<ol type="1">
<li><p><strong>All three phenotype-prediction tools agree: the predicted microbial phenotypes of the gut microbiome do not differ significantly between the four adenoma follow-up groups</strong> (Recurrence_1/2 vs Non_recurrence_1/2). This holds for classical phenotypes (Traitar), life-history traits (microTrait) and CAZyme families (dbCAN3), and for both per-feature tests (Kruskal-Wallis + BH) and multivariate tests (PERMANOVA).</p></li>
<li><p><strong>The strongest raw-p candidates are biologically coherent but not significant.</strong> Across tools they point to carbohydrate metabolism — polysaccharide transport (microTrait, p = 0.0115), CBM27/GH26/GH125 (dbCAN3, p = 0.004–0.010), trehalose utilization (Traitar) — and the plant- polysaccharide module (p = 0.178). These are hypothesis-generating leads, not confirmations.</p></li>
<li><p><strong>Multivariate structure is absent.</strong> PERMANOVA R² ≈ 0.012–0.015 with P = 0.20–0.55 across all three tools and both group sets; betadisper is non-significant except for the 6-group Traitar comparison (P = 0.043, a dispersion rather than location effect). The groups occupy the same multivariate space.</p></li>
<li><p><strong>Implications.</strong> At n = 236 (4-group) the cohort is underpowered to detect per-feature differences after correction for 60–300 tests. The targeted module approach (4–7 tests) is the right scale and shows the expected direction (plant/mucin glycan degradation slightly higher in Non_recurrence) without reaching significance. Next steps: (i) increase sample size; (ii) focus on pre-specified modules; (iii) integrate with the paired delta analysis (see the delta report), which uses the same tools on within-individual changes.</p></li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>