[package]
name = "my-nav-panel"
version = "0.7.0"
description = "AlpeHuez developer panel desktop app"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }
serde_json = "1"

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "unstable", "tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-updater = "2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
md5 = "0.7"
sysinfo = "0.30"
base64 = "0.22"
percent-encoding = "2"
rusqlite = { version = "0.31", features = ["bundled", "backup"] }
ureq = "2"
include_dir = "0.7"
keyring = "3"
sha2 = "0.10"
zip = "4"
window-vibrancy = "0.8.0"
raw-window-handle = "0.6"

[target.'cfg(windows)'.dependencies]
winreg = "0.52"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_Graphics_Dwm"] }

[target.'cfg(not(target_os = "android"))'.dependencies]
arboard = "3"

[lib]
name = "my_nav_panel_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
